services:
  - type: web
    name: django-backend
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend.wsgi"
    envVars:
      - key: SECRET_KEY
        value: your-production-secret-key
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: your-app-name.onrender.com
      - key: DATABASE_URL
        value: postgres://username:password@hostname:port/dbname
      - key: CORS_ALLOWED_ORIGINS
        value: http://localhost:3000,https://your-flutter-app-domain.com